config/routes.rb
Rails.application.routes.draw do


  resources :tasks, only: [:index, :new, :edit, :show]

  post 'tasks', to: "tasks#create"

  patch 'tasks/:id', to: "tasks#update"

  delete 'tasks/:id', to: "tasks#destroy", as: :destroy_task



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tasks/_index.html.erb
<h1>Tasks#index</h1>
<ul>
  <h3>
    <% @tasks.each do |task| %>
    <li><%= link_to task.name, task_path(task.id) %>
    </li>
    <%end%>
  </h3>
</ul>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>


<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<%= render "index" %>

<%= link_to "Create new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>


<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>


<h3>
  <%= "#{@task.name}:" %>
  <%= "#{@task.description}" %>
  <%= "(DONE)" if @task.done? %>
  <%= "(TODO)" if @task.done? == false %>
</h3>

<%= link_to "edit task", edit_task_path %>
<%= link_to "destroy task", destroy_task_path,
method: :delete,
data: {confirm: "Are you sure"} %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>